import React from "react";
import { Link } from "react-router-dom";
import "./Login.scss"; // Import your CSS file

function Login() {
     return (
          <section className="vh-100 gradient-custom-light">
               <div className="container py-5 h-100">
                    <div className="row d-flex justify-content-center align-items-center h-100">
                         <div className="col-12 col-md-8 col-lg-6 col-xl-5">
                              <div className="card bg-light text-dark">
                                   <div className="card-body text-center">
                                        <div className="mb-md-5 mt-md-4 pb-5">
                                             <h2 className="fw-bold mb-2 text-uppercase">
                                                  Login
                                             </h2>
                                             <p className="text-black-50 mb-5">
                                                  Please enter your login and
                                                  password!
                                             </p>

                                             <div className="form-outline form-white mb-4">
                                                  <input
                                                       type="email"
                                                       id="typeEmailX"
                                                       className="form-control form-control-lg"
                                                  />
                                                  <label
                                                       className="form-label"
                                                       htmlFor="typeEmailX"
                                                  >
                                                       Email
                                                  </label>
                                             </div>

                                             <div className="form-outline form-white mb-4">
                                                  <input
                                                       type="password"
                                                       id="typePasswordX"
                                                       className="form-control form-control-lg"
                                                  />
                                                  <label
                                                       className="form-label"
                                                       htmlFor="typePasswordX"
                                                  >
                                                       Password
                                                  </label>
                                             </div>

                                             <p className="small mb-5 pb-lg-2">
                                                  <a
                                                       className="text-black-50"
                                                       href="#!"
                                                  >
                                                       Forgot password?
                                                  </a>
                                             </p>

                                             <button
                                                  className="btn btn-outline-dark btn-lg px-5"
                                                  type="submit"
                                             >
                                                  Login
                                             </button>

                                             <div className="d-flex justify-content-center text-center mt-4 pt-1">
                                                  <a
                                                       href="#!"
                                                       className="text-dark"
                                                  >
                                                       <i className="fab fa-facebook-f fa-lg"></i>
                                                  </a>
                                                  <a
                                                       href="#!"
                                                       className="text-dark"
                                                  >
                                                       <i className="fab fa-twitter fa-lg mx-4 px-2"></i>
                                                  </a>
                                                  <a
                                                       href="#!"
                                                       className="text-dark"
                                                  >
                                                       <i className="fab fa-google fa-lg"></i>
                                                  </a>
                                             </div>
                                        </div>

                                        <div>
                                             <p className="mb-0">
                                                  Don't have an account?{" "}
                                                  <Link
                                                       to="/signup"
                                                       className="text-black-50 fw-bold"
                                                  >
                                                       Sign Up
                                                  </Link>
                                             </p>
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>
               </div>
          </section>
     );
}

export default Login;
